### ISSUE TITLE
What is Burp Suite IP?

### ISSUE THREAD

**Issue by KirillBorodin** [ptswarm/reFlutter#47]
Morning, trying to figure out the usage of your tool.
I found it very useful and wish you all the best in further app improvements.

Only one issue I've found is: 
The example usage of the tool is quite difficult to understand for the users that didn't work with Burp Suite.

For example: 
What IP should I insert here:
`Please enter your Burp Suite IP:`

I've tried: 
- `127.0.0.1`
- My Android Emulator's IP: `10.0.2.15`
- My Mac's Local IP: `192.168.*.*`

The reason why am I asking about that is:
When I run:
 `adb logcat -e reflutter | sed 's/.*DartVM//' >> reflutter.txt` 
and launch the signed apk file: 
`release.RE-aligned-debugSigned.apk` on my Emulator I don't see any logs in `reflutter.txt`;

What did I do wrong?

Thank you

**Comment by Impact-I** [comment]
Hi @KirillBorodin ,
Could you provide `SnapshotHash:` or apk file?

BurpSuite IP is the ip of your proxy server (which must support transparent proxy mode). I recommend using BurpSuite in invisible proxy mode.

Thanks!

**Comment by KirillBorodin** [comment]
SnapshotHash: `d56742caf7b3b3f4bd2df93a9bbb5503`

My BurpSuite options:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/29107059/155293121-758e3e3d-704f-4d92-91b8-f452ea5337d0.png">

**Comment by Impact-I** [comment]
@KirillBorodin , I just tested the app with engine version `d56742caf7b3b3f4bd2df93a9bbb5503`
It works on my device. Try using AndroidStudio to view logcat and use AVD instead of QEMU as emulator. But it is better to use a real device.

**Comment by KirillBorodin** [comment]
Thank you for testing!
I'll try to run on real device and let you know.

**Comment by KirillBorodin** [comment]
So, what IP should I set when I run reflutter <file.apk> ?

**Comment by Impact-I** [comment]
@KirillBorodin , Specify the ip on which you are running BurpSuite
Please note the emulator must be: `arm64, arm32`; But not `x86_64`

**Comment by KirillBorodin** [comment]
> @KirillBorodin , Specify the ip on which you are running BurpSuite Please note the emulator must be: `arm64, arm32`; But not `x86_64`

Thank you!

I suppose the problem was with my emulator, going to try on real device.
